name: CI
on:
  pull_request:
  push:
    branches:
      - main
env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-C debuginfo=0 -D warnings"
jobs:
  cargo-deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check ${{ matrix.checks }}
        uses: dnaka91/actions/deny-check@main
        with:
          checks: ${{ matrix.checks }}
